steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - assets-bqloader
      - --region=asia-northeast1
      - --source=.
      - --trigger-resource=asset_trend
      - --trigger-event=google.storage.object.finalize
      - --runtime=python39
      - --entry-point=bqloader
      - --service-account=assets-bqloader@slackbot-288310.iam.gserviceaccount.com
